networks:
  webnet:
    driver: bridge

services:
  nginx-static:
    image: nginx:alpine
    container_name: static_site_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      #- ./frontend/nginx80.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/nginx443.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - webnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./data/database.db
    command: >
      poetry run uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
    restart: unless-stopped
    networks:
      - webnet

  bot:
    build:
      context: ./backend
    container_name: telegram_bot
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./data/database.db
    command: python -B -m app.bot.main
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - webnet

  # util-контейнер, НЕ сервис
  certbot:
    image: certbot/certbot
    profiles: ["certbot"]
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - webnet

