version: "3.9"

services:
  nginx-static:
    image: nginx:alpine
    container_name: static_site_container
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./data/database.db
    restart: unless-stopped
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  bot:
    build:
      context: ./backend
    container_name: telegram_bot
    restart: unless-stopped
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./data/database.db
    command: ["python", "-B", "-m", "app.bot.main"]
    depends_on:
      - backend
